name: snap-sharp # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Quick .NET example on how to package snaps # 79 char long summary
description: |
  Quick sample app to demonstrate how to build and package
  your own .NET applications as snaps.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
  snap-sharp:
    command: usr/bin/SnapSharp
    environment:
      LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/usr/lib

parts:
  snap-sharp:
    # See 'snapcraft plugins'
    plugin: dump
    source: .
    build-packages:
    - dotnet-sdk-6.0
    stage-packages:
    - libicu70
    - libx11-6
    - libice6
    - libsm6
    override-build: |
      dotnet publish -o ./dist -c Release -r linux-x64 -p:PublishSingleFile=true --self-contained true
      cp ./dist/* $SNAPCRAFT_PART_INSTALL
      rm $SNAPCRAFT_PART_INSTALL/*.pdb
    organize:
      SnapSharp: usr/bin/
      libHarfBuzzSharp.so: usr/lib/
      libSkiaSharp.so: usr/lib/

